cleanNamespace: true
packages:
  - name: my-package-name
    environment:
      - beeperino
      - booperino
    actions:
      - name: my-action-name
        annotations:
          - provide-api-key: abc123
          - whisk-auth annotation: abc123
        clean: true
        sequence: 
          - utils/split
          - utils/sort
        webSecure: true
        shared: true
        # these are web content configs
        bucket:
          - prefixPath: "prefix"
          - strip: 5
          - mainPageSuffic: "suffix"
          - notFoundPage: "page"
          - clean: true
          - useCache: true
          - remoteBuild: true
          - localBuild: true
